/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NN_jframes;

/**
 *
 * @author Diego Armando
 */
public class NN_agregarCitaClienteExiste extends javax.swing.JFrame {

    NN_JframeAdmin manager;
    NN_agregarCita agregarCitaMenu;
    NN_EditarCita editarCitaMenu;
    boolean fromEdit;
    /**
     * Creates new form NN_agregarCitaClienteExiste
     */
    public NN_agregarCitaClienteExiste() {
        initComponents();
        manager = NN_MainClass.getManager();
        agregarCitaMenu = manager.managerAgregarCita;
        editarCitaMenu = manager.managerCitaEdit;
        fromEdit = false;
        try{
            fromEdit = editarCitaMenu.edit;
        } catch (Exception e){
            
        }
        //System.out.println("fromEdit="+fromEdit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B_yes = new javax.swing.JButton();
        B_no = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente existente");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(490, 150));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" en la base de datos?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 440, 20));

        B_yes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        B_yes.setText("Si");
        B_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_yesActionPerformed(evt);
            }
        });
        getContentPane().add(B_yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        B_no.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        B_no.setText("No");
        B_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_noActionPerformed(evt);
            }
        });
        getContentPane().add(B_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("El cliente ya existe, ¿desea asociar esta cita con el cliente que esta registrado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 460, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_noActionPerformed
        // TODO add your handling code here:
        if(fromEdit){
            editarCitaMenu.reset();    
            editarCitaMenu.enable(true);
        }
        else{
            agregarCitaMenu.reset();
            agregarCitaMenu.enable(true);
        }
        fromEdit = false;
        this.dispose();
    }//GEN-LAST:event_B_noActionPerformed

    private void B_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_yesActionPerformed
        // TODO add your handling code here:
        if(fromEdit){
        editarCitaMenu.finishAppointment();
        editarCitaMenu.setEnabled(true);
        }
        else{
        agregarCitaMenu.finishAppointment();
        agregarCitaMenu.setEnabled(true);            
        }
        this.dispose();
    }//GEN-LAST:event_B_yesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NN_agregarCitaClienteExiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NN_agregarCitaClienteExiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NN_agregarCitaClienteExiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NN_agregarCitaClienteExiste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NN_agregarCitaClienteExiste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_no;
    private javax.swing.JButton B_yes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
