/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NN_jframes;

import BusinessObjects.Appointment;
import BusinessObjects.Client;
import BusinessObjects.Employee;
import BusinessObjects.Payment;
import BusinessObjects.Product;
import Managers.DatabaseManager;
import java.awt.Dimension;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego Armando
 */
public class NN_editarProducto extends javax.swing.JFrame {
    
    DatabaseManager db;
    boolean busy = false;
    NN_JframeAdmin manager;
    NN_InventarioMain productMenu;
    
    /**
     * Creates new form NN_agregarCliente
     */
    public NN_editarProducto() {
        initComponents();
        hidebttn();
        setMinimumSize(new Dimension(600,340).getSize());
        db = NN_MainClass.db;
        manager = NN_MainClass.getManager();
        productMenu = manager.managerInventoryMain;
        int newid = db.getMax("PRODUCT");
        T_id.setText(Integer.toString(newid));
        LocalDate rightnow = java.time.LocalDate.now();
        //KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(keyEventDispatcher);
        Product selProduct = db.getProductById(manager.managerInventoryMain.selectedId);
        T_id.setText(Integer.toString(selProduct.getId()));
        B_nombre.setText(selProduct.getName());
        B_cantidad.setText(Float.toString(selProduct.getQuantity()));
        B_proveedor.setText(selProduct.getSupplier());
        B_costo.setText(Float.toString(selProduct.getCost()));
        CBO_unit.setSelectedItem(selProduct.getUnit());
        
    }

    public void hidebttn(){
                
        B_agregar.setOpaque(false);
        B_agregar.setContentAreaFilled(false); //to make the content area transparent
        B_agregar.setBorderPainted(false); //to make the borders transparent
               
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_agregar = new javax.swing.JButton();
        T_Id = new javax.swing.JLabel();
        T_id = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        T_Cantidad = new javax.swing.JLabel();
        B_cantidad = new javax.swing.JTextField();
        B_nombre = new javax.swing.JTextField();
        T_Cantidad1 = new javax.swing.JLabel();
        B_proveedor = new javax.swing.JTextField();
        T_Cantidad2 = new javax.swing.JLabel();
        B_costo = new javax.swing.JTextField();
        T_Cantidad3 = new javax.swing.JLabel();
        CBO_unit = new javax.swing.JComboBox<>();
        T_Success = new javax.swing.JLabel();
        buttonS1 = new javax.swing.JLabel();
        Line6 = new javax.swing.JLabel();
        Line1 = new javax.swing.JLabel();
        Line2 = new javax.swing.JLabel();
        Line3 = new javax.swing.JLabel();
        Line4 = new javax.swing.JLabel();
        Line5 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Editar producto");
        setLocation(new java.awt.Point(300, 230));
        setMinimumSize(new java.awt.Dimension(600, 320));
        setPreferredSize(new java.awt.Dimension(600, 320));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_agregar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        B_agregar.setForeground(new java.awt.Color(255, 255, 255));
        B_agregar.setText("Editar");
        B_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(B_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 275, 70, 30));

        T_Id.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_Id.setForeground(new java.awt.Color(0, 102, 102));
        T_Id.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        T_Id.setText("Id de Producto");
        getContentPane().add(T_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 172, -1));

        T_id.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        T_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_id.setText("-");
        getContentPane().add(T_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 227, -1));

        Telefono.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Telefono.setForeground(new java.awt.Color(0, 102, 102));
        Telefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Telefono.setText("Nombre del producto");
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 151, -1));

        T_Cantidad.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_Cantidad.setForeground(new java.awt.Color(0, 102, 102));
        T_Cantidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        T_Cantidad.setText("Cantidad");
        getContentPane().add(T_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 105, -1));

        B_cantidad.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        B_cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(B_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 130, -1));

        B_nombre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        B_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(B_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 350, -1));

        T_Cantidad1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_Cantidad1.setForeground(new java.awt.Color(0, 102, 102));
        T_Cantidad1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        T_Cantidad1.setText("Proveedor");
        getContentPane().add(T_Cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 105, -1));

        B_proveedor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        B_proveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(B_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 350, -1));

        T_Cantidad2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_Cantidad2.setForeground(new java.awt.Color(0, 102, 102));
        T_Cantidad2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        T_Cantidad2.setText("Costo");
        getContentPane().add(T_Cantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 105, -1));

        B_costo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        B_costo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(B_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 130, -1));

        T_Cantidad3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_Cantidad3.setForeground(new java.awt.Color(0, 102, 102));
        T_Cantidad3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        T_Cantidad3.setText("Unidad");
        getContentPane().add(T_Cantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 105, -1));

        CBO_unit.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        CBO_unit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pza", "Ml", "Mg", "Lt", "Kg" }));
        getContentPane().add(CBO_unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        T_Success.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        T_Success.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_Success.setText("-");
        getContentPane().add(T_Success, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 267, 450, 30));

        buttonS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/pagoMain/pagoMain_button.png"))); // NOI18N
        getContentPane().add(buttonS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 100, 40));

        Line6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/pagoMain/pagoMain_line.png"))); // NOI18N
        getContentPane().add(Line6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 220, -1, 40));

        Line1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/pagoMain/pagoMain_line.png"))); // NOI18N
        getContentPane().add(Line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, -1, 20));

        Line2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/pagoMain/pagoMain_line.png"))); // NOI18N
        getContentPane().add(Line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, -1, 10));

        Line3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/pagoMain/pagoMain_line.png"))); // NOI18N
        getContentPane().add(Line3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, -1, 40));

        Line4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/pagoMain/pagoMain_line.png"))); // NOI18N
        getContentPane().add(Line4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 120, -1, 70));

        Line5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/pagoMain/pagoMain_line.png"))); // NOI18N
        getContentPane().add(Line5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, -1, 70));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/productoMain/productoMain_background.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        productMenu.refreshTable();
        productMenu.enable(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void B_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agregarActionPerformed
        confirm();
    }//GEN-LAST:event_B_agregarActionPerformed
   
    public void confirm(){
        boolean amountOk = true;
        boolean costOk = true;
        float amount = 0;
        float cost = 0;
        try{
            amount = Float.parseFloat(B_cantidad.getText());
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "La cantidad debe ser solo numeros", "Error en la cantidad", JOptionPane.INFORMATION_MESSAGE);
            amountOk = false;
        }
        try{
            cost = Float.parseFloat(B_costo.getText());
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "El costo debe ser solo numeros", "Error en el costo", JOptionPane.INFORMATION_MESSAGE);
            amountOk = false;
        }
        if(costOk && amountOk){
            finishProduct();                
        }
        productMenu.refreshTable();
    }
    
    public void finishProduct(){
        Product newProduct = new Product();
        String prodName = B_nombre.getText();
        String provName = B_proveedor.getText();
        float amountVal = Float.parseFloat(B_cantidad.getText());
        float costVal = Float.parseFloat(B_costo.getText());
        String Unit = CBO_unit.getSelectedItem().toString();
        newProduct.setId(Integer.parseInt(T_id.getText()));
        newProduct.setName(prodName);
        newProduct.setQuantity(amountVal);
        newProduct.setCost(costVal);
        newProduct.setSupplier(provName);
        newProduct.setUnit(Unit);
        db.updateProduct(newProduct);
        T_Success.setText("Se actualizo correctamente el producto");
        
    }
    
    
    public void reset(){
    }
    
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        busy = false;
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        busy = true;
    }//GEN-LAST:event_formWindowLostFocus
    
    public void updateAppointmentNewClientData(Client appClient){
    }
    
    public void updateAppointmentOldClientData(Client appClient){
 
    }
        
    /*KeyEventDispatcher keyEventDispatcher = new KeyEventDispatcher() {
        @Override
        public boolean dispatchKeyEvent(final KeyEvent e) {
            if (e.getID() == KeyEvent.KEY_TYPED) {
            String eString = e.toString();
            if(eString.contains("Intro") && !busy){
                confirm();
            }
        }
        // Pass the KeyEvent to the next KeyEventDispatcher in the chain
            return false;
        }
    };*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NN_agregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NN_agregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NN_agregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NN_agregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NN_agregarEmpleado().setVisible(true);
            }
        });
    }

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton B_agregar;
    private javax.swing.JTextField B_cantidad;
    private javax.swing.JTextField B_costo;
    private javax.swing.JTextField B_nombre;
    private javax.swing.JTextField B_proveedor;
    private javax.swing.JComboBox<String> CBO_unit;
    private javax.swing.JLabel Line1;
    private javax.swing.JLabel Line2;
    private javax.swing.JLabel Line3;
    private javax.swing.JLabel Line4;
    private javax.swing.JLabel Line5;
    private javax.swing.JLabel Line6;
    private javax.swing.JLabel T_Cantidad;
    private javax.swing.JLabel T_Cantidad1;
    private javax.swing.JLabel T_Cantidad2;
    private javax.swing.JLabel T_Cantidad3;
    private javax.swing.JLabel T_Id;
    private javax.swing.JLabel T_Success;
    private javax.swing.JLabel T_id;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel buttonS1;
    // End of variables declaration//GEN-END:variables
}
