/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NN_jframes;

import BusinessObjects.Appointment;
import BusinessObjects.Client;
import BusinessObjects.Payment;
import Managers.DatabaseManager;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

/**
 *
 * @author Diego Armando
 */
public class NN_Estadistica extends javax.swing.JFrame {
    DatabaseManager db;
    public NN_JframeAdmin manager;
    /**
     * Creates new form NN_Estadistica
     */
    public NN_Estadistica() {
        initComponents();
        hidebttn();
        setMinimumSize(new Dimension(490,630).getSize());
        db = NN_MainClass.db;
        manager = NN_MainClass.getManager();
        CBO_año.setSelectedItem("2019");
        statsPay();
        displayTop();
    }

    public void hidebttn(){
                
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false); //to make the content area transparent
        jButton1.setBorderPainted(false); //to make the borders transparent
               
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T_month1 = new javax.swing.JLabel();
        T_month2 = new javax.swing.JLabel();
        T_month3 = new javax.swing.JLabel();
        T_month4 = new javax.swing.JLabel();
        T_month5 = new javax.swing.JLabel();
        T_month6 = new javax.swing.JLabel();
        T_month7 = new javax.swing.JLabel();
        T_month8 = new javax.swing.JLabel();
        T_month9 = new javax.swing.JLabel();
        T_month10 = new javax.swing.JLabel();
        T_month11 = new javax.swing.JLabel();
        T_month12 = new javax.swing.JLabel();
        PB_1 = new javax.swing.JProgressBar();
        PB_2 = new javax.swing.JProgressBar();
        PB_3 = new javax.swing.JProgressBar();
        PB_4 = new javax.swing.JProgressBar();
        PB_5 = new javax.swing.JProgressBar();
        PB_6 = new javax.swing.JProgressBar();
        PB_7 = new javax.swing.JProgressBar();
        PB_8 = new javax.swing.JProgressBar();
        PB_9 = new javax.swing.JProgressBar();
        PB_10 = new javax.swing.JProgressBar();
        PB_11 = new javax.swing.JProgressBar();
        PB_12 = new javax.swing.JProgressBar();
        CBO_año = new javax.swing.JComboBox<>();
        CBO_pago = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Line3 = new javax.swing.JLabel();
        Line2 = new javax.swing.JLabel();
        Line1 = new javax.swing.JLabel();
        T_month1Amount1 = new javax.swing.JLabel();
        T_month1Amount2 = new javax.swing.JLabel();
        T_month1Amount3 = new javax.swing.JLabel();
        T_month1Amount4 = new javax.swing.JLabel();
        T_month1Amount5 = new javax.swing.JLabel();
        T_month1Amount6 = new javax.swing.JLabel();
        T_month1Amount7 = new javax.swing.JLabel();
        T_month1Amount8 = new javax.swing.JLabel();
        T_month1Amount9 = new javax.swing.JLabel();
        T_month1Amount10 = new javax.swing.JLabel();
        T_month1Amount11 = new javax.swing.JLabel();
        T_month1Amount12 = new javax.swing.JLabel();
        T_totalAmount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        T_client1 = new javax.swing.JLabel();
        T_client2 = new javax.swing.JLabel();
        T_client3 = new javax.swing.JLabel();
        T_month13 = new javax.swing.JLabel();
        Line4 = new javax.swing.JLabel();
        buttonS2 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Estadisticas");
        setLocation(new java.awt.Point(300, 230));
        setMinimumSize(new java.awt.Dimension(480, 610));
        setPreferredSize(new java.awt.Dimension(480, 610));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T_month1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1.setForeground(new java.awt.Color(153, 0, 51));
        T_month1.setText("Diciembre");
        getContentPane().add(T_month1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        T_month2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month2.setForeground(new java.awt.Color(153, 0, 51));
        T_month2.setText("Enero");
        getContentPane().add(T_month2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        T_month3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month3.setForeground(new java.awt.Color(153, 0, 51));
        T_month3.setText("Febrero");
        getContentPane().add(T_month3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        T_month4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month4.setForeground(new java.awt.Color(153, 0, 51));
        T_month4.setText("Marzo");
        getContentPane().add(T_month4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        T_month5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month5.setForeground(new java.awt.Color(153, 0, 51));
        T_month5.setText("Abril");
        getContentPane().add(T_month5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        T_month6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month6.setForeground(new java.awt.Color(153, 0, 51));
        T_month6.setText("Mayo");
        getContentPane().add(T_month6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        T_month7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month7.setForeground(new java.awt.Color(153, 0, 51));
        T_month7.setText("Junio");
        getContentPane().add(T_month7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        T_month8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month8.setForeground(new java.awt.Color(153, 0, 51));
        T_month8.setText("Julio");
        getContentPane().add(T_month8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        T_month9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month9.setForeground(new java.awt.Color(153, 0, 51));
        T_month9.setText("Agosto");
        getContentPane().add(T_month9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        T_month10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month10.setForeground(new java.awt.Color(153, 0, 51));
        T_month10.setText("Septiembre");
        getContentPane().add(T_month10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        T_month11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month11.setForeground(new java.awt.Color(153, 0, 51));
        T_month11.setText("Octubre");
        getContentPane().add(T_month11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        T_month12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month12.setForeground(new java.awt.Color(153, 0, 51));
        T_month12.setText("Noviembre");
        getContentPane().add(T_month12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        PB_1.setBackground(new java.awt.Color(255, 255, 255));
        PB_1.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 230, -1));

        PB_2.setBackground(new java.awt.Color(255, 255, 255));
        PB_2.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 230, -1));

        PB_3.setBackground(new java.awt.Color(255, 255, 255));
        PB_3.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 230, -1));

        PB_4.setBackground(new java.awt.Color(255, 255, 255));
        PB_4.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 230, -1));

        PB_5.setBackground(new java.awt.Color(255, 255, 255));
        PB_5.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 230, -1));

        PB_6.setBackground(new java.awt.Color(255, 255, 255));
        PB_6.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 230, -1));

        PB_7.setBackground(new java.awt.Color(255, 255, 255));
        PB_7.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 230, -1));

        PB_8.setBackground(new java.awt.Color(255, 255, 255));
        PB_8.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 230, -1));

        PB_9.setBackground(new java.awt.Color(255, 255, 255));
        PB_9.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 230, -1));

        PB_10.setBackground(new java.awt.Color(255, 255, 255));
        PB_10.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 230, -1));

        PB_11.setBackground(new java.awt.Color(255, 255, 255));
        PB_11.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 230, -1));

        PB_12.setBackground(new java.awt.Color(255, 255, 255));
        PB_12.setForeground(new java.awt.Color(255, 0, 102));
        getContentPane().add(PB_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 230, -1));

        CBO_año.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CBO_año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        CBO_año.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBO_añoItemStateChanged(evt);
            }
        });
        getContentPane().add(CBO_año, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, -1));

        CBO_pago.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CBO_pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Utilidad", "No. de citas" }));
        CBO_pago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBO_pagoItemStateChanged(evt);
            }
        });
        getContentPane().add(CBO_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 140, -1));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 555, 80, 30));

        Line3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/reporteMain/reporteMain_line.png"))); // NOI18N
        getContentPane().add(Line3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 580, -1, 10));

        Line2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/reporteMain/reporteMain_line.png"))); // NOI18N
        getContentPane().add(Line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 540, -1, 10));

        Line1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/reporteMain/reporteMain_line.png"))); // NOI18N
        getContentPane().add(Line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 500, -1, 10));

        T_month1Amount1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount1.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount1.setText("-");
        getContentPane().add(T_month1Amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 70, -1));

        T_month1Amount2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount2.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount2.setText("-");
        getContentPane().add(T_month1Amount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 70, -1));

        T_month1Amount3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount3.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount3.setText("-");
        getContentPane().add(T_month1Amount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 70, -1));

        T_month1Amount4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount4.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount4.setText("-");
        getContentPane().add(T_month1Amount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 70, -1));

        T_month1Amount5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount5.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount5.setText("-");
        getContentPane().add(T_month1Amount5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 70, -1));

        T_month1Amount6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount6.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount6.setText("-");
        getContentPane().add(T_month1Amount6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 70, -1));

        T_month1Amount7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount7.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount7.setText("-");
        getContentPane().add(T_month1Amount7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 70, -1));

        T_month1Amount8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount8.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount8.setText("-");
        getContentPane().add(T_month1Amount8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 70, -1));

        T_month1Amount9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount9.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount9.setText("-");
        getContentPane().add(T_month1Amount9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 70, -1));

        T_month1Amount10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount10.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount10.setText("-");
        getContentPane().add(T_month1Amount10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 70, -1));

        T_month1Amount11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount11.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount11.setText("-");
        getContentPane().add(T_month1Amount11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 70, -1));

        T_month1Amount12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month1Amount12.setForeground(new java.awt.Color(153, 0, 51));
        T_month1Amount12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_month1Amount12.setText("-");
        getContentPane().add(T_month1Amount12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 70, -1));

        T_totalAmount.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_totalAmount.setForeground(new java.awt.Color(153, 0, 51));
        T_totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T_totalAmount.setText("-");
        getContentPane().add(T_totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 70, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes mas frecuentes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        T_client1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_client1.setForeground(new java.awt.Color(153, 0, 51));
        T_client1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        T_client1.setText("-");
        getContentPane().add(T_client1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 270, -1));

        T_client2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_client2.setForeground(new java.awt.Color(153, 0, 51));
        T_client2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        T_client2.setText("-");
        getContentPane().add(T_client2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 270, -1));

        T_client3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_client3.setForeground(new java.awt.Color(153, 0, 51));
        T_client3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        T_client3.setText("-");
        getContentPane().add(T_client3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 270, -1));

        T_month13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        T_month13.setForeground(new java.awt.Color(153, 0, 51));
        T_month13.setText("Total");
        getContentPane().add(T_month13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        Line4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/reporteMain/reporteMain_tab2.png"))); // NOI18N
        getContentPane().add(Line4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 440, -1, 40));

        buttonS2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/reporteMain/reporteMain_button.png"))); // NOI18N
        getContentPane().add(buttonS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 100, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/reporteMain/reporteMain_background.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void statsApp(){
        float totaladd = 0;
        float month01Sum = 0;
        float month02Sum = 0;
        float month03Sum = 0;
        float month04Sum = 0;
        float month05Sum = 0;
        float month06Sum = 0;
        float month07Sum = 0;
        float month08Sum = 0;
        float month09Sum = 0;
        float month10Sum = 0;
        float month11Sum = 0;
        float month12Sum = 0;
        ResultSet allApps = db.getAppointmentByYear(Integer.parseInt(CBO_año.getSelectedItem().toString()));
        try{          
            while(allApps.next()){
                Appointment nApp = new Appointment();
                nApp.setId(allApps.getInt("ID"));
                nApp.setId_c(allApps.getInt("ID_C"));
                nApp.setId_e(allApps.getInt("ID_E"));
                nApp.setDay(allApps.getInt("DAY"));
                nApp.setMonth(allApps.getInt("MONTH"));
                nApp.setYear(allApps.getInt("YEAR"));
                nApp.setHour(allApps.getString("HOUR"));
                nApp.setCost(allApps.getFloat("COST"));
                nApp.setReason(allApps.getString("REASON"));
                nApp.setHourValue(allApps.getFloat("HOURVALUE"));
                totaladd = totaladd + 1;
                switch (nApp.getMonth()){
                           case 0:  month01Sum = month01Sum + 1;
                           break;
                           case 1:  month02Sum = month02Sum + 1;
                           break;
                           case 2:  month03Sum = month03Sum + 1;
                           break;
                           case 3:  month04Sum = month04Sum + 1;
                           break;
                           case 4:  month05Sum = month05Sum + 1;
                           break;
                           case 5:  month06Sum = month06Sum + 1;
                           break;
                           case 6:  month07Sum = month07Sum + 1;
                           break;
                           case 7:  month08Sum = month08Sum + 1;
                           break;
                           case 8:  month09Sum = month09Sum + 1;
                           break;
                           case 9:  month10Sum = month10Sum + 1;
                           break;
                           case 10:  month11Sum = month11Sum + 1;
                           break;
                           case 11:  month12Sum = month12Sum + 1;
                           break;
                       }
            }
            int mensual[] = new int[12];
            mensual[0] = Math.round(month01Sum);
            mensual[1] = Math.round(month02Sum);
            mensual[2] = Math.round(month03Sum);
            mensual[3] = Math.round(month04Sum);
            mensual[4] = Math.round(month05Sum);
            mensual[5] = Math.round(month06Sum);
            mensual[6] = Math.round(month07Sum);
            mensual[7] = Math.round(month08Sum);
            mensual[8] = Math.round(month09Sum);
            mensual[9] = Math.round(month10Sum);
            mensual[10] = Math.round(month11Sum);
            mensual[11] = Math.round(month12Sum);
            float maxV = maxValue(mensual);
            maxV = setMaxApp(maxV);
            float month1P = (month01Sum / maxV) * 100;
            float month2P = (month02Sum / maxV) * 100;
            float month3P = (month03Sum / maxV) * 100;
            float month4P = (month04Sum / maxV) * 100;
            float month5P = (month05Sum / maxV) * 100;
            float month6P = (month06Sum / maxV) * 100;
            float month7P = (month07Sum / maxV) * 100;
            float month8P = (month08Sum / maxV) * 100;
            float month9P = (month09Sum / maxV) * 100;
            float month10P = (month10Sum / maxV) * 100;
            float month11P = (month11Sum / maxV) * 100;
            float month12P = (month12Sum / maxV) * 100;
            PB_1.setValue(Math.round(month1P));
            PB_2.setValue(Math.round(month2P));
            PB_3.setValue(Math.round(month3P));
            PB_4.setValue(Math.round(month4P));
            PB_5.setValue(Math.round(month5P));
            PB_6.setValue(Math.round(month6P));
            PB_7.setValue(Math.round(month7P));
            PB_8.setValue(Math.round(month8P));
            PB_9.setValue(Math.round(month9P));
            PB_10.setValue(Math.round(month10P));
            PB_11.setValue(Math.round(month11P));
            PB_12.setValue(Math.round(month12P));
            T_month1Amount1.setText(Float.toString(month01Sum));
            T_month1Amount2.setText(Float.toString(month02Sum));
            T_month1Amount3.setText(Float.toString(month03Sum));
            T_month1Amount4.setText(Float.toString(month04Sum));
            T_month1Amount5.setText(Float.toString(month05Sum));
            T_month1Amount6.setText(Float.toString(month06Sum));
            T_month1Amount7.setText(Float.toString(month07Sum));
            T_month1Amount8.setText(Float.toString(month08Sum));
            T_month1Amount9.setText(Float.toString(month09Sum));
            T_month1Amount10.setText(Float.toString(month10Sum));
            T_month1Amount11.setText(Float.toString(month11Sum));
            T_month1Amount12.setText(Float.toString(month12Sum));
            T_totalAmount.setText(Float.toString(totaladd));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }
    
    public void displayTop(){
        int top[];
        top = new int[] {0,0,0};
        int c = 0;
        ResultSet tops = db.getAppointmentByYearGrouped(Integer.parseInt(CBO_año.getSelectedItem().toString()));
        try{          
            while(tops.next() && c <= 2){
                top[c] = tops.getInt("ID_C");
                c++;
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        T_client1.setText(idToClientName(top[0]));
        T_client2.setText(idToClientName(top[1]));
        T_client3.setText(idToClientName(top[2]));
        
    }
    
    public String idToClientName(int id){
        String name = null;
        Client newClient = db.getClientebyId(id);
        if(newClient.getId()<=0){
            name = "Inexistente";
        }
        else{
            String fName = newClient.getFirstName();
            String lName = newClient.getLastName();
            name = fName + " " + lName;
        }
        
        return name;
    }
    
    public void statsPay(){
        float totaladd = 0;
        float month01Sum = 0;
        float month02Sum = 0;
        float month03Sum = 0;
        float month04Sum = 0;
        float month05Sum = 0;
        float month06Sum = 0;
        float month07Sum = 0;
        float month08Sum = 0;
        float month09Sum = 0;
        float month10Sum = 0;
        float month11Sum = 0;
        float month12Sum = 0;
        ResultSet allPays = db.getPaymentByYear(Integer.parseInt(CBO_año.getSelectedItem().toString()));
        try{          
            while(allPays.next()){
                Payment nPay = new Payment();
                nPay.setId(allPays.getInt("ID"));
                nPay.setId_a(allPays.getInt("ID_A"));
                nPay.setId_e(allPays.getInt("ID_E"));
                nPay.setAmount(allPays.getFloat("AMOUNT"));
                nPay.setDay(allPays.getInt("DAY"));
                nPay.setMonth(allPays.getInt("MONTH"));
                nPay.setYear(allPays.getInt("YEAR"));
                totaladd = totaladd + nPay.getAmount();
                switch (nPay.getMonth()){
                           case 0:  month01Sum = month01Sum + nPay.getAmount();
                           break;
                           case 1:  month02Sum = month02Sum + nPay.getAmount();
                           break;
                           case 2:  month03Sum = month03Sum + nPay.getAmount();
                           break;
                           case 3:  month04Sum = month04Sum + nPay.getAmount();
                           break;
                           case 4:  month05Sum = month05Sum + nPay.getAmount();
                           break;
                           case 5:  month06Sum = month06Sum + nPay.getAmount();
                           break;
                           case 6:  month07Sum = month07Sum + nPay.getAmount();
                           break;
                           case 7:  month08Sum = month08Sum + nPay.getAmount();
                           break;
                           case 8:  month09Sum = month09Sum + nPay.getAmount();
                           break;
                           case 9:  month10Sum = month10Sum + nPay.getAmount();
                           break;
                           case 10:  month11Sum = month11Sum + nPay.getAmount();
                           break;
                           case 11:  month12Sum = month12Sum + nPay.getAmount();
                           break;
                       }
            }
            int mensual[] = new int[12];
            mensual[0] = Math.round(month01Sum);
            mensual[1] = Math.round(month02Sum);
            mensual[2] = Math.round(month03Sum);
            mensual[3] = Math.round(month04Sum);
            mensual[4] = Math.round(month05Sum);
            mensual[5] = Math.round(month06Sum);
            mensual[6] = Math.round(month07Sum);
            mensual[7] = Math.round(month08Sum);
            mensual[8] = Math.round(month09Sum);
            mensual[9] = Math.round(month10Sum);
            mensual[10] = Math.round(month11Sum);
            mensual[11] = Math.round(month12Sum);
            float maxV = maxValue(mensual);
            maxV = setMaxPay(maxV);
            float month1P = (month01Sum / maxV) * 100;
            float month2P = (month02Sum / maxV) * 100;
            float month3P = (month03Sum / maxV) * 100;
            float month4P = (month04Sum / maxV) * 100;
            float month5P = (month05Sum / maxV) * 100;
            float month6P = (month06Sum / maxV) * 100;
            float month7P = (month07Sum / maxV) * 100;
            float month8P = (month08Sum / maxV) * 100;
            float month9P = (month09Sum / maxV) * 100;
            float month10P = (month10Sum / maxV) * 100;
            float month11P = (month11Sum / maxV) * 100;
            float month12P = (month12Sum / maxV) * 100;
            PB_1.setValue(Math.round(month1P));
            PB_2.setValue(Math.round(month2P));
            PB_3.setValue(Math.round(month3P));
            PB_4.setValue(Math.round(month4P));
            PB_5.setValue(Math.round(month5P));
            PB_6.setValue(Math.round(month6P));
            PB_7.setValue(Math.round(month7P));
            PB_8.setValue(Math.round(month8P));
            PB_9.setValue(Math.round(month9P));
            PB_10.setValue(Math.round(month10P));
            PB_11.setValue(Math.round(month11P));
            PB_12.setValue(Math.round(month12P));
            T_month1Amount1.setText(Float.toString(month01Sum));
            T_month1Amount2.setText(Float.toString(month02Sum));
            T_month1Amount3.setText(Float.toString(month03Sum));
            T_month1Amount4.setText(Float.toString(month04Sum));
            T_month1Amount5.setText(Float.toString(month05Sum));
            T_month1Amount6.setText(Float.toString(month06Sum));
            T_month1Amount7.setText(Float.toString(month07Sum));
            T_month1Amount8.setText(Float.toString(month08Sum));
            T_month1Amount9.setText(Float.toString(month09Sum));
            T_month1Amount10.setText(Float.toString(month10Sum));
            T_month1Amount11.setText(Float.toString(month11Sum));
            T_month1Amount12.setText(Float.toString(month12Sum));
            T_totalAmount.setText(Float.toString(totaladd));
            } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }
    
    public void displayTop1(){
        String nameArray[];
        
        T_client1.setText("");
    }
    
    public int maxValue(int array[]){
        List<Integer> list = new ArrayList<Integer>();
        for (int i = 0; i < array.length; i++) {
        list.add(array[i]);
        } 
        return Collections.max(list);
    }
    
    public float setMaxPay(float val){
        float max = 0;
        while(val > max){
            max = max + 500;
        }
        return max;
    }
    
    public float setMaxApp(float val){
        float max = 0;
        while(val > max){
            max = max + 5;
        }
        return max;
    }
        
    public void select(){
        if(CBO_pago.getSelectedItem().toString().equals("Utilidad")){
            statsPay();
        }
        else{
            statsApp();
        }
    }
    
    private void CBO_pagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBO_pagoItemStateChanged
        // TODO add your handling code here:
        select();
        displayTop();
    }//GEN-LAST:event_CBO_pagoItemStateChanged

    private void CBO_añoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBO_añoItemStateChanged
        // TODO add your handling code here:
        select();
        displayTop();
    }//GEN-LAST:event_CBO_añoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        manager.openMainMenu();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        manager.openMainMenu();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NN_Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NN_Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NN_Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NN_Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NN_Estadistica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JComboBox<String> CBO_año;
    private javax.swing.JComboBox<String> CBO_pago;
    private javax.swing.JLabel Line1;
    private javax.swing.JLabel Line2;
    private javax.swing.JLabel Line3;
    private javax.swing.JLabel Line4;
    private javax.swing.JProgressBar PB_1;
    private javax.swing.JProgressBar PB_10;
    private javax.swing.JProgressBar PB_11;
    private javax.swing.JProgressBar PB_12;
    private javax.swing.JProgressBar PB_2;
    private javax.swing.JProgressBar PB_3;
    private javax.swing.JProgressBar PB_4;
    private javax.swing.JProgressBar PB_5;
    private javax.swing.JProgressBar PB_6;
    private javax.swing.JProgressBar PB_7;
    private javax.swing.JProgressBar PB_8;
    private javax.swing.JProgressBar PB_9;
    private javax.swing.JLabel T_client1;
    private javax.swing.JLabel T_client2;
    private javax.swing.JLabel T_client3;
    private javax.swing.JLabel T_month1;
    private javax.swing.JLabel T_month10;
    private javax.swing.JLabel T_month11;
    private javax.swing.JLabel T_month12;
    private javax.swing.JLabel T_month13;
    private javax.swing.JLabel T_month1Amount1;
    private javax.swing.JLabel T_month1Amount10;
    private javax.swing.JLabel T_month1Amount11;
    private javax.swing.JLabel T_month1Amount12;
    private javax.swing.JLabel T_month1Amount2;
    private javax.swing.JLabel T_month1Amount3;
    private javax.swing.JLabel T_month1Amount4;
    private javax.swing.JLabel T_month1Amount5;
    private javax.swing.JLabel T_month1Amount6;
    private javax.swing.JLabel T_month1Amount7;
    private javax.swing.JLabel T_month1Amount8;
    private javax.swing.JLabel T_month1Amount9;
    private javax.swing.JLabel T_month2;
    private javax.swing.JLabel T_month3;
    private javax.swing.JLabel T_month4;
    private javax.swing.JLabel T_month5;
    private javax.swing.JLabel T_month6;
    private javax.swing.JLabel T_month7;
    private javax.swing.JLabel T_month8;
    private javax.swing.JLabel T_month9;
    private javax.swing.JLabel T_totalAmount;
    private javax.swing.JLabel buttonS2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
