    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NN_jframes;
import BusinessObjects.Employee;
import Managers.DatabaseManager;
import NN_jframes.NN_JframeAdmin;
import java.awt.Dimension;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.Window;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author Diego Armando
 */
public class NN_login extends javax.swing.JFrame {
    
    DatabaseManager db;
    boolean busy = false;
    
    public NN_JframeAdmin manager;
    /**
     * Creates new form NN_login
     */
    public NN_login() {
        initComponents();
        hidebttn();
        setMinimumSize(new Dimension(706,529).getSize());
        db = NN_MainClass.db;
        manager = NN_MainClass.getManager();
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(keyEventDispatcher);

    }

    public void hidebttn(){
                
        bLogin.setOpaque(false);
        bLogin.setContentAreaFilled(false); //to make the content area transparent
        bLogin.setBorderPainted(false); //to make the borders transparent
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        bLogin = new javax.swing.JButton();
        inputline2 = new javax.swing.JLabel();
        inputline1 = new javax.swing.JLabel();
        inputline = new javax.swing.JLabel();
        TitleLine = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setLocation(new java.awt.Point(300, 230));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUsername.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(239, 123, 107));
        tfUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUsername.setText("Username");
        tfUsername.setBorder(null);
        tfUsername.setOpaque(false);
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 204, -1));

        tfPassword.setForeground(new java.awt.Color(239, 118, 107));
        tfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPassword.setText("PASSWORD");
        tfPassword.setBorder(null);
        tfPassword.setOpaque(false);
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });
        getContentPane().add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 204, -1));

        bLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bLogin.setForeground(new java.awt.Color(255, 255, 255));
        bLogin.setText("Login");
        bLogin.setOpaque(false);
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 433, 80, 30));

        inputline2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputline2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/LogIn/Login_Button.png"))); // NOI18N
        getContentPane().add(inputline2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 180, 40));

        inputline1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/LogIn/Login_Inputline.png"))); // NOI18N
        getContentPane().add(inputline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, 20));

        inputline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/LogIn/Login_Inputline.png"))); // NOI18N
        getContentPane().add(inputline, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, 20));

        TitleLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/LogIn/Login_Titleline.png"))); // NOI18N
        getContentPane().add(TitleLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 165, 155));
        jLabel1.setText("    ina's       ails");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(239, 165, 155));
        jLabel2.setText("N          N");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 165, 155));
        jLabel3.setText("Sistema de informacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/NinaNails/LogIn/Login_Background.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 740, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_bLoginActionPerformed

    public void login(){
        String inputuser = tfUsername.getText();
        String inputpass = tfPassword.getText();
        {
            Employee accessUser = db.getEmployeeByUsername(inputuser);
            String correctpass = accessUser.getPass();
            if(inputpass.equals(correctpass)){
                manager.setLoggeduser(accessUser);
                manager.openMainMenu();
                this.dispose();
            }
            else{
               JOptionPane.showMessageDialog(null, "Usuario y password no coinciden", "Error en el usuario/password", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
    }
    
    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        // TODO add your handling code here:
        if(tfUsername.getText().equals("Username")){
            tfUsername.setText("");
        }
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        // TODO add your handling code here:
        if(tfPassword.getText().equals("PASSWORD")){
            tfPassword.setText("");
        }
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        // TODO add your handling code here:
        if(tfUsername.getText().equals("")){
            tfUsername.setText("Username");
        }
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        // TODO add your handling code here:
        if(tfPassword.getText().equals("")){
            tfPassword.setText("PASSWORD");
        }
    }//GEN-LAST:event_tfPasswordFocusLost

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        Scanner keyboard = new Scanner(System.in);
        int myint = keyboard.nextInt();
    }//GEN-LAST:event_formKeyPressed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        busy = true;
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        busy = false;
    }//GEN-LAST:event_formWindowGainedFocus

    KeyEventDispatcher keyEventDispatcher = new KeyEventDispatcher() {
        @Override
        public boolean dispatchKeyEvent(final KeyEvent e) {
            if (e.getID() == KeyEvent.KEY_TYPED) {
            String eString = e.toString();
            if(eString.contains("Intro") && !busy){
                login();
            }
        }
        // Pass the KeyEvent to the next KeyEventDispatcher in the chain
            return false;
        }
    };
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NN_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NN_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NN_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NN_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NN_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel TitleLine;
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel inputline;
    private javax.swing.JLabel inputline1;
    private javax.swing.JLabel inputline2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
